// CLI help text. Name lists come from the report / output registries
// so help stays in sync with wired-up entries.

import {outputNames} from "../recommend/select-output.ts"
import {inspectorNames} from "../inspect/inspector-names.ts"
import {reportNames} from "../report/report-names.ts"

export function usage(): string {
    return [
        "Usage: ts-survey <command> [options] [files...]",
        "",
        "Commands:",
        "  help                        Show this help (also: no args, -h, --help)",
        "  report [reports...]         Survey the codebase; print Markdown reports",
        "  reformat                    Apply the reports' recommendations to disk",
        "  list                        List files with export / usage counts",
        "  inspect [inspectors...]     Per-file analysis (exports, importers, ...)",
        "  move <source...> <dest>     Move .ts files and rewrite import paths",
        "",
        "report (read; the primary mode):",
        "  report                      Run every report and print the survey Markdown",
        "  report --<report>...        Restrict to the named reports (e.g. --semicolons --indent)",
        `                              Known reports: ${reportNames.join(", ")}`,
        "  --output <name>             Suppress Markdown and emit the named output instead",
        `                              Known outputs: ${outputNames.join(", ")}`,
        "",
        "reformat (write; applies the reports' recommendations to disk):",
        "  reformat                    Apply the recommended settings to every file",
        "  --indent <N|tab>            Override indent width or use tabs",
        "  --semicolons on|off         Override semicolon insertion",
        "  --new-line lf|crlf          Override end-of-line",
        "  --bracket-spacing on|off    Override inner-brace spacing",
        "  --organize-imports on|off   Toggle organize-imports (default: on)",
        "  --dry-run                   Print paths instead of writing",
        "",
        "list (read; file export / usage listing):",
        "  list                        List every file with export / unused / importer counts",
        "  --no-exports                Only files that export nothing",
        "  --no-importers              Only files no other file imports",
        "  --unused-exports            Only files with unused exports",
        "                              (multiple list filters combine with OR)",
        "",
        "inspect (read; per-file analysis):",
        "  inspect                     Run every inspector on every file",
        "  inspect --<inspector>...    Restrict to the named inspectors",
        `                              Known inspectors: ${inspectorNames.join(", ")}`,
        "",
        "move (write; relocate .ts files and rewrite the import paths):",
        "  move <source...> <dest>     mv-style: dest may be a directory (multi-source)",
        "                              or a target filename (single-source rename).",
        "                              Paths are resolved against the tsconfig dir",
        "                              (same basis the other commands use).",
        "  --dry-run                   Print the planned moves and touched files",
        "",
        "Project (mirrors `tsc -p`):",
        "  -p, --project <path>        Path to a tsconfig.json or a directory",
        "                              that contains one. Defaults to `-p .`.",
        "",
        "Files (applies to all read/write commands):",
        "  [files...]                  Restrict to the given files; globs are allowed,",
        "                              resolved against the tsconfig dir. Default: all.",
    ].join("\n")
}
