// CLI help text. Name lists come from the report / output registries
// so help stays in sync with wired-up entries.

import {inspectorNames} from "../common/inspector-names.ts"
import {reportNames} from "../common/report-names.ts"
import {emitNames} from "./report/select-emitter.ts"

export function usage(): string {
    const reportFlags = reportNames.map((name) => `--${name}`).join(" ")
    const inspectorFlags = inspectorNames.map((name) => `--${name}`).join(" ")
    const emitFlags = emitNames.map((name) => `--emit ${name}`).join(" / ")

    return [
        "Usage: ts-refine <command> [options] [files...]",
        "",
        "Commands:",
        "  help                        Show this help (also: no args, -h, --help)",
        "  list                        List files with export / usage counts",
        "  report [--<report>...]      Survey the codebase; print Markdown reports",
        "  format                      Apply inferred conventions and organize imports",
        "  inspect [--<inspector>...]  Per-file analysis (exports, importers, ...)",
        "  move <source...> <dest>     Move .ts files and rewrite import paths",
        "  rename --from <a> --to <b>  Rename an exported identifier project-wide",
        "",
        "list (read; file export / usage listing):",
        "  list                        List every file with export / unused / importer counts",
        "  --no-exports                Only files that export nothing",
        "  --no-importers              Only files no other file imports",
        "  --unused-exports            Only files with unused exports",
        "                              (multiple list filters combine with OR)",
        "",
        "report (read; the primary mode):",
        "  report                      Run every report and print the survey Markdown",
        "  report --<report>...        Restrict to the named reports:",
        `                              ${reportFlags}`,
        "  --emit <name>               Suppress Markdown and emit the named output instead",
        `                              ${emitFlags}`,
        "                              prettier: .prettierrc JSON; ts-refine: runnable format command",
        "",
        "format (write; follows inferred conventions):",
        "  format                      Apply the recommended settings and organize imports",
        "  --indent <N|tab>            Override indent width or use tabs",
        "  --semicolons on|off         Override semicolon insertion",
        "  --new-line lf|crlf          Override end-of-line",
        "  --bracket-spacing on|off    Override inner-brace spacing",
        "  --organize-imports on|off   Toggle organize-imports (default: on)",
        "  --check                     Report only; exit non-zero if any file would change",
        "",
        "inspect (read; per-file analysis):",
        "  inspect                     Run every inspector on every file",
        "  inspect --<inspector>...    Restrict to the named inspectors:",
        `                              ${inspectorFlags}`,
        "",
        "move (write; relocate .ts files and rewrite the import paths):",
        "  move <source...> <dest>     mv-style: dest may be a directory (multi-source)",
        "                              or a target filename (single-source rename).",
        "                              Paths are resolved against the tsconfig dir",
        "                              (same basis the other commands use).",
        "",
        "rename (write; rename an exported identifier and every reference):",
        "  rename --from <a> --to <b>  Rename the export `a` to `b` project-wide,",
        "                              updating importers and usages (aliases kept).",
        "  --from <a.b> --to <a.c>     A dotted name renames a member in place: a",
        "                              namespace member, or an interface/class property.",
        "  rename --from ... <file>    Scope a non-unique name to its defining file.",
        "",
        "Global options (may appear before or after the command):",
        "  -p, --project <path>        Path to a tsconfig.json or a directory",
        "                              that contains one. Defaults to `-p .`.",
        "  --dry-run                   format/move/rename only: print instead of writing",
        "  -h, --help                  Show this help",
        "",
        "File filters (report/format/list/inspect):",
        "  [files...]                  Restrict to the given files; globs are allowed,",
        "                              resolved against the tsconfig dir. Default: all.",
        "",
        "Command paths:",
        "  move <source...> <dest>     Source and destination paths, not filters",
        "  rename --from ... <file>    Optional file that disambiguates the export",
    ].join("\n")
}
